// Generated by npm run generate:browser-support. Do not edit manually.
export const browserSupportFeatures = {
  "light-dark": {
    "name": "light-dark()",
    "baseline": "low",
    "baselineLowDate": "2024-05-13",
    "baselineHighDate": null,
    "support": {
      "chrome": "123",
      "edge": "123",
      "firefox": "120",
      "safari": "17.5",
      "node": null
    }
  },
  "contrast-color": {
    "name": "contrast-color()",
    "baseline": "low",
    "baselineLowDate": "2026-04-10",
    "baselineHighDate": null,
    "support": {
      "chrome": "147",
      "edge": "147",
      "firefox": "146",
      "safari": "26",
      "node": null
    }
  },
  "interpolate-size": {
    "name": "interpolate-size",
    "baseline": false,
    "baselineLowDate": null,
    "baselineHighDate": null,
    "support": {
      "chrome": "129",
      "edge": "129",
      "firefox": null,
      "safari": null,
      "node": null
    }
  },
  "container-queries": {
    "name": "Container queries",
    "baseline": "high",
    "baselineLowDate": "2023-02-14",
    "baselineHighDate": "2025-08-14",
    "support": {
      "chrome": "105",
      "edge": "105",
      "firefox": "110",
      "safari": "16",
      "node": null
    }
  },
  "backdrop-filter": {
    "name": "backdrop-filter",
    "baseline": "low",
    "baselineLowDate": "2024-09-16",
    "baselineHighDate": null,
    "support": {
      "chrome": "76",
      "edge": "79",
      "firefox": "103",
      "safari": "18",
      "node": null
    }
  },
  "popover": {
    "name": "Popover",
    "baseline": "low",
    "baselineLowDate": "2025-01-27",
    "baselineHighDate": null,
    "support": {
      "chrome": "116",
      "edge": "116",
      "firefox": "125",
      "safari": "17",
      "node": null
    }
  },
  "anchor-name": {
    "name": "Anchor positioning",
    "baseline": "low",
    "baselineLowDate": "2026-01-13",
    "baselineHighDate": null,
    "support": {
      "chrome": "125",
      "edge": "125",
      "firefox": "147",
      "safari": "26",
      "node": null
    }
  },
  "starting-style": {
    "name": "@starting-style",
    "baseline": "low",
    "baselineLowDate": "2024-08-06",
    "baselineHighDate": null,
    "support": {
      "chrome": "117",
      "edge": "117",
      "firefox": "129",
      "safari": "17.5",
      "node": null
    }
  },
  "transition-behavior": {
    "name": "transition-behavior",
    "baseline": "low",
    "baselineLowDate": "2024-08-06",
    "baselineHighDate": null,
    "support": {
      "chrome": "117",
      "edge": "117",
      "firefox": "129",
      "safari": "17.4",
      "node": null
    }
  },
  "temporal": {
    "name": "Temporal",
    "baseline": false,
    "baselineLowDate": null,
    "baselineHighDate": null,
    "support": {
      "chrome": "144",
      "edge": "144",
      "firefox": "139",
      "safari": null,
      "node": "26"
    }
  },
  "dialog-closedby": {
    "name": "<dialog closedby>",
    "baseline": false,
    "baselineLowDate": null,
    "baselineHighDate": null,
    "support": {
      "chrome": "134",
      "edge": "134",
      "firefox": "141",
      "safari": null,
      "node": null
    }
  },
  "invoker-commands": {
    "name": "Invoker commands",
    "baseline": "low",
    "baselineLowDate": "2025-12-12",
    "baselineHighDate": null,
    "support": {
      "chrome": "135",
      "edge": "135",
      "firefox": "144",
      "safari": "26.2",
      "node": null
    }
  },
  "has": {
    "name": ":has()",
    "baseline": "high",
    "baselineLowDate": "2023-12-19",
    "baselineHighDate": "2026-06-19",
    "support": {
      "chrome": "105",
      "edge": "105",
      "firefox": "121",
      "safari": "15.4",
      "node": null
    }
  },
  "scrollbar-color": {
    "name": "scrollbar-color",
    "baseline": "low",
    "baselineLowDate": "2025-12-12",
    "baselineHighDate": null,
    "support": {
      "chrome": "121",
      "edge": "121",
      "firefox": "64",
      "safari": "26.2",
      "node": null
    }
  },
  "scrollbar-gutter": {
    "name": "scrollbar-gutter",
    "baseline": "low",
    "baselineLowDate": "2024-12-11",
    "baselineHighDate": null,
    "support": {
      "chrome": "94",
      "edge": "94",
      "firefox": "97",
      "safari": "18.2",
      "node": null
    }
  },
  "scrollbar-width": {
    "name": "scrollbar-width",
    "baseline": "low",
    "baselineLowDate": "2024-12-11",
    "baselineHighDate": null,
    "support": {
      "chrome": "121",
      "edge": "121",
      "firefox": "64",
      "safari": "18.2",
      "node": null
    }
  },
  "popover-hint": {
    "name": "popover=\"hint\"",
    "baseline": false,
    "baselineLowDate": null,
    "baselineHighDate": null,
    "support": {
      "chrome": "133",
      "edge": "133",
      "firefox": "149",
      "safari": null,
      "node": null
    }
  },
  "interest-invokers": {
    "name": "Interest invokers",
    "baseline": false,
    "baselineLowDate": null,
    "baselineHighDate": null,
    "support": {
      "chrome": "142",
      "edge": "142",
      "firefox": null,
      "safari": null,
      "node": null
    }
  }
} as const;

export const browserSupportProfiles = {
  "accordion": [
    "light-dark",
    "contrast-color",
    "interpolate-size"
  ],
  "alert": [
    "light-dark",
    "contrast-color",
    "container-queries"
  ],
  "autocomplete": [
    "light-dark",
    "contrast-color",
    "backdrop-filter",
    "popover",
    "anchor-name",
    "starting-style",
    "transition-behavior"
  ],
  "avatar": [
    "light-dark"
  ],
  "badge": [
    "light-dark",
    "contrast-color"
  ],
  "barcode": [
    "light-dark",
    "contrast-color"
  ],
  "button": [
    "light-dark",
    "contrast-color"
  ],
  "card": [
    "light-dark",
    "contrast-color"
  ],
  "checkbox": [
    "light-dark",
    "contrast-color",
    "popover",
    "anchor-name"
  ],
  "chip": [
    "light-dark",
    "contrast-color"
  ],
  "datepicker": [
    "light-dark",
    "contrast-color",
    "backdrop-filter",
    "popover",
    "anchor-name",
    "starting-style",
    "transition-behavior",
    "temporal"
  ],
  "dialog": [
    "light-dark",
    "contrast-color",
    "dialog-closedby",
    "invoker-commands",
    "starting-style",
    "transition-behavior"
  ],
  "drawer": [
    "light-dark",
    "contrast-color",
    "dialog-closedby",
    "invoker-commands",
    "starting-style",
    "transition-behavior"
  ],
  "input": [
    "light-dark",
    "contrast-color",
    "has",
    "popover",
    "anchor-name",
    "starting-style",
    "transition-behavior"
  ],
  "loading": [
    "light-dark"
  ],
  "menu": [
    "light-dark",
    "backdrop-filter",
    "popover",
    "anchor-name",
    "starting-style",
    "transition-behavior"
  ],
  "popover": [
    "light-dark",
    "contrast-color",
    "popover",
    "invoker-commands",
    "anchor-name",
    "starting-style",
    "transition-behavior"
  ],
  "progress": [
    "light-dark"
  ],
  "radio": [
    "light-dark",
    "contrast-color",
    "popover",
    "anchor-name"
  ],
  "select": [
    "light-dark",
    "backdrop-filter",
    "popover",
    "anchor-name",
    "starting-style",
    "transition-behavior"
  ],
  "skeleton": [
    "light-dark"
  ],
  "sonner": [
    "light-dark",
    "contrast-color",
    "has",
    "interpolate-size"
  ],
  "switch": [
    "light-dark",
    "contrast-color",
    "popover",
    "anchor-name"
  ],
  "table": [
    "light-dark",
    "contrast-color",
    "scrollbar-color",
    "scrollbar-gutter",
    "scrollbar-width"
  ],
  "tabs": [
    "light-dark",
    "contrast-color",
    "has",
    "anchor-name",
    "scrollbar-width"
  ],
  "tooltip": [
    "light-dark",
    "popover-hint",
    "interest-invokers",
    "starting-style",
    "transition-behavior"
  ],
  "tree": [
    "light-dark",
    "interpolate-size"
  ]
} as const;
