import { TestBed } from '@angular/core/testing';
import { SonnerService } from './sonner.service';

describe('SonnerService', () => {
  let service: SonnerService;

  beforeEach(() => {
    TestBed.configureTestingModule({});
    service = TestBed.inject(SonnerService);
    service.reset();
  });

  it('should create default toasts with autogenerated ids', () => {
    const id = service.show('Saved');

    expect(typeof id).toBe('number');
    expect(service.toasts()).toEqual([
      expect.objectContaining({
        id,
        title: 'Saved',
        type: 'default',
        dismissible: true,
      }),
    ]);
  });

  it('should update an existing toast by id without moving duplicates into the stack', () => {
    service.show('Saving', { id: 'request' });
    service.success('Saved', undefined, { id: 'request' });

    expect(service.toasts()).toHaveLength(1);
    expect(service.toasts()[0]).toEqual(
      expect.objectContaining({ id: 'request', title: 'Saved', type: 'success' }),
    );
  });

  it('should reset an inherited loading duration when the same toast settles', () => {
    service.loading('Saving', undefined, { id: 'request' });

    expect(service.toasts()[0].duration).toBe(Number.POSITIVE_INFINITY);

    service.success('Saved', undefined, { id: 'request' });

    expect(service.toasts()[0]).toEqual(
      expect.objectContaining({ id: 'request', title: 'Saved', type: 'success' }),
    );
    expect(service.toasts()[0].duration).toBeUndefined();
  });

  it('should map error convenience calls to the destructive toast type', () => {
    service.error('Failed');

    expect(service.toasts()[0].type).toBe('destructive');
  });

  it('should mark programmatically dismissed toasts for animated removal', () => {
    const id = service.show('Saved');

    service.dismiss(id);

    expect(service.toasts()).toHaveLength(1);
    expect(service.toasts()[0]).toEqual(
      expect.objectContaining({ id, delete: true, dismissing: true }),
    );
  });
});
